### ISSUE TITLE
Move to Qt6

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#794]
* [x] switch to CMake
* [x] make QE compatible with Qt6
* [x] fix Qt6 deprecation warnings

**Comment by fvacek** [comment]
* https://github.com/Quick-Event/quickbox/pull/791
* https://github.com/Quick-Event/quickbox/pull/792
* https://github.com/Quick-Event/quickbox/pull/793

**Comment by arnost00** [comment]
Wa want to drop support for Qt5 ?

**Comment by arnost00** [comment]
I've asked because of supported Windows version. Not every computer for event organization has latest Windows.
[Qt6 supported platforms](https://doc.qt.io/qt-6/supported-platforms.html) - Win11, Win10
[Qt5 supported platforms](https://doc.qt.io/qt-5/supported-platforms.html) - Win11, Win10, Win8.1, Win7

**Comment by fvacek** [comment]
I plan to keep qt5 support as long as possible, but yes, I like to switch to qt6. There is more fun with it. :)
